### ISSUE TITLE
Getting "Error: Request failed with status code 401" with the correct credentials

### ISSUE THREAD

**Issue by kroy94** [2201gh-team-saturn/grace-shopper-main#116]
I'm attempting to login as Murphy with PW 123 and getting this error status. Not sure what's going on but it's creating a work stoppage for me as I attempt to update Cart Associatoins.

**Comment by kroy94** [comment]
Reverted back to the last time I pulled from github and attempted to login again, got a new error this time: 

"column "cartId" does not exist"

**Comment by LeahHarlow** [comment]
I'm sure you tried this but did you npm install again and reseed?

**Comment by LeahHarlow** [comment]
I didn't think any of the associations were updated in the last merge did I miss that?

**Comment by kroy94** [comment]
They weren't! I'm updating them now but can't login to check out the cart now that I've logged out

**Comment by kroy94** [comment]
Figured out what the issue was! May added a hook on our User table to capitalize the the first letter of the username.
